## Nornir Config File
---
core:

  num_workers: 100

inventory:

  plugin: "nornir.plugins.inventory.simple.SimpleInventory"

  options:

    host_file: "/home/eve/Nornir/inventory/hosts.yml"

    group_file: "/home/eve/Nornir/inventory/groups.yml"

    defaults_file: "/home/eve/Nornir/inventory/defaults.yml"
